--- 
abstract: Perl interface to Alec Muffett's Cracklib.
author: Dan Sully <daniel@cpan.org>
build_requires: 
  Pod::Coverage: 0.19
  Test::More: 0.47
  Test::Pod::Coverage: 1.08
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Crypt-Cracklib
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.004
version: 1.4
